[package]
name = "myers-ed"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"

[dev-dependencies]
criterion = "0.7"

[[bench]]
name = "bench"
harness = false

[features]
avx512 = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
